### PR TITLE
Align reqPnl and cancelPnl function names with official API.

### PR DESCRIPTION
**Pull request by mfrener**
There is a typo an reqPnl and cancelPnl.
On official API they both start end with upper-case L: reqPnL and cancelPnL

### CODE REVIEW

**Comment by ceddybi** [comment]
@mfrener have you tested if this breaks any implementation?

**Comment by ceddybi** [comment]
@mfrener also could you update the readme and the examples please, thank you very much

**Comment by mfrener** [comment]
> @mfrener have you tested if this breaks any implementation?

Works with my implementation. readme is updated (arguments on the reqPnL where also missing), but haven't update the samples (will do ;) )

**Comment by mfrener** [comment]
src/reqPnl.ts is fixed + squashed to 1 commit

**Review by ceddybi — APPROVED** [review]

**Pull request merged**
