### PR TITLE
v165

### PR DESCRIPTION
**Pull request by ctoesca**
Hello, 
I use your IB library which works very well, but I needed "FRACTIONAL SIZE SUPPORT" (v163), so I upgraded the library to v165. 
Is it possible to integrate these changes into your version ? 

Thank you.

### CODE REVIEW

**Comment by ctoesca** [comment]
I realize I haven't touched api-next.

**Comment by rylorin** [comment]
Can you please add the '../../api/historical/HistoricalSession' missing file?

**Comment by rylorin** [comment]
Thank you for your good work!
I did some regression tests and didn't notice anything wrong.

**Review by Tsopic — APPROVED** [review]
Thanks for the contribution 🚀

**Pull request merged**
