### PR TITLE
- Port public API to Typescript, update to IB API version 9.76 and ad…

### PR DESCRIPTION
**Pull request by mfrener**
This the final PR for the Typescript & API 9.76 support overhaul.
The code has been changed completely. It is all Typescript 3 notation now.

There are breaking API changes. 
This API does now align with official API. So "ib.contract.stock('AAPL')" is gone, but is now "new Stock('APPL')" ect. pp.

The I/O code has also been reworked to be more maintainable and it now also supports all of the API 9.76 features. 

If you know that there are active users on this lib, we might want to do a major version increase to signal the breaking changes
(not sure how that auto-version bump works, feel free to commit changes to overhaul/port-ts branch to make a jump to 1.0.0)

I have ported my App and to new lib tested it (an option market scanner) and works - now even with V100Plus features :)
Also there are a couple of unit tests on api.spec.ts to run a 'smoke test' against a an account with a least 1 position (doesn't do any trades, just request positions).

Examples folder has been removed as it was outdated. 
If we find more contributes, a small node.js portfolio-watcher example would be nice to have to demo usage.

If there issues / bug reports, feel to assign it me, will have a look.
Back to my other projects in the meanwhile ;)

### CODE REVIEW

**Comment by ceddybi** [comment]
Thank you very much @mfrener 🙏🙏🙏, the auto bump looks for `major`, `minor` or `patch` from any git commit message, I just added one sample comment that adds the default export, 

Looks all good from my end, please feel free to merge ✅

**Review by ceddybi — APPROVED** [review]

**Comment by ajanian** [comment]
Hey guys.  I'm trying to test out this stuff and I am having trouble even importing.  I think there is something wrong with the packaging.  The npm package I have is empty except for the license, README and package.json.

I'll take a look to see if I have done something wrong but I think there was an issue with the distribution.

image

**Comment by ajanian** [comment]
Yes, there is an issue with the npm packaging:

```curl --output ib-1.0.0.tgz https://registry.npmjs.org/@stoqey/ib/-/ib-1.0.0.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2915  100  2915    0     0  12196      0 --:--:-- --:--:-- --:--:-- 12145
```

```
tar -xzvf ib-1.0.0.tgz
package/LICENSE
package/package.json
package/README.md
```

**Comment by mfrener** [comment]
Yeah same for me if install via npm, although the /dist folder is populated correctly with "npm run build" from repo.
@ceddybi is there any adaption on npm publish script needed? Built code is still is on /dist, it just has been changed (not familiar all with the npm publish)

**Comment by ceddybi** [comment]
@ajanian @mfrener had forgotten `prepublishOnly` to run `build` script, should be good now with the `v1.0.1` patch

https://github.com/stoqey/ib/commit/d53fa8492621ced2985e3e14046aa38f3804c9a3

**Comment by mfrener** [comment]
works now 👍 👍

**Pull request merged**
