### PR TITLE
Api next

### PR DESCRIPTION
**Pull request by Tsopic**

### CODE REVIEW

**Comment by mfrener** [comment]
Hmm not sure if we want to mege to master already. 
I'm pretty confident that current API is close to the final one, but there will be some changes for sure and I don't want ppl jump onto this until we can guarantee an API that won't change on a daily basis =)
Maybe there is way to have a "preview" release channel? So you do something like yarn add @stoqey/ib@next to get next instead of the master? So ppl can try it, but it's not on official release yet.
Don't do if this make more than 5min of work - it's not worth it - just need some time for testing / playing arround make is sure public APIs are stable before we go to master.

**Comment by Tsopic** [comment]
Totally agree with you @mfrener. Lemme know when you think it's ready. I'll try to implement my order functionality on it.

And go for a test run.

It's a draft branch, so it's not even ready for review ;) 

Let's use the draft branches for easier reviewing while still in development.

**Comment by mfrener** [comment]
Jep - major for focus now should to establish consistent design patterns for all type of functions, what work fast are reliable and easy are to understand for dev. When we have that it should be (no, must be) easy to missing the functions.
i.e. here is very good point https://github.com/stoqey/ib/issues/54 so there will be one rework on how we handle reqId's - fixing the mentioned issue and introducing the Subscription-cache / lookup at the same time. So better not have too many functions yet, because we need to change it all we change the pattern (but adding the order functions is definitly worth it).

**Comment by netshade** [comment]
Did a pass through read on this, just offering a few comments:

1. I think I understand correctly in that, generally, "cached" values are cached in the `Subscription` created for a specific request; so, invoking the word cache here does not mean that values from one call to something like `reqContractDetails` would necessarily affect values in a concurrent request to `reqContractDetails` ( just as example ). If that's true, cool, that seems good. Upon reading cache at first, I was worried that there might be an attempt to marshal data into a global cache of some form, which seems like it would have some nasty surprising behaviors in wait for anyone using this library.
2. `reqMarketData` however, has an odd effect. The cache essentially acts as an accumulation of values seen by prior ticks. This may just be a matter of documentation, but it seems like it would be possible to receive a tick update caused by something like an option computation tick update or what have you, and you, the receiver of updates, might also assume that the bid/ask is up to date because you did in fact receive a tick update. However, it's only a *subset* of the tick that has been updated, and if you were automating interactions w/ the market based on the ticket update, your view of the world could be pretty stale. Maybe allowing a user specified expiry on the data, such that, if the data received is older than some amount, the prior tick is thrown away as it is no longer considered valid. As mentioned tho, that could just be the concern of the caller, and the documentation tells them such.
3. I do not often work on web frontend things, so I cannot say w/ any real authority, but it seems like the majority of the JS ecosystem is adopting Promises as a way to handle asynchrony. I only mention it to say you may find yourself unnecessarily explaining the philosophy behind your choice to use RxJS / subscriptions in the future more than you like, as the community expectation further drifts towards expecting a `Promise`. I have no comment on the merit of the decision, I should note, just on the disconnect between what seems to be the current JS community trend and this.

**Comment by mfrener** [comment]
> Did a pass through read on this, just offering a few comments:
> 
> 1. I think I understand correctly in that, generally, "cached" values are cached in the `Subscription` created for a specific request; so, invoking the word cache here does not mean that values from one call to something like `reqContractDetails` would necessarily affect values in a concurrent request to `reqContractDetails` ( just as example ). If that's true, cool, that seems good. Upon reading cache at first, I was worried that there might be an attempt to marshal data into a global cache of some form, which seems like it would have some nasty surprising behaviors in wait for anyone using this library.
> 2. `reqMarketData` however, has an odd effect. The cache essentially acts as an accumulation of values seen by prior ticks. This may just be a matter of documentation, but it seems like it would be possible to receive a tick update caused by something like an option computation tick update or what have you, and you, the receiver of updates, might also assume that the bid/ask is up to date because you did in fact receive a tick update. However, it's only a _subset_ of the tick that has been updated, and if you were automating interactions w/ the market based on the ticket update, your view of the world could be pretty stale. Maybe allowing a user specified expiry on the data, such that, if the data received is older than some amount, the prior tick is thrown away as it is no longer considered valid. As mentioned tho, that could just be the concern of the caller, and the documentation tells them such.
> 3. I do not often work on web frontend things, so I cannot say w/ any real authority, but it seems like the majority of the JS ecosystem is adopting Promises as a way to handle asynchrony. I only mention it to say you may find yourself unnecessarily explaining the philosophy behind your choice to use RxJS / subscriptions in the future more than you like, as the community expectation further drifts towards expecting a `Promise`. I have no comment on the merit of the decision, I should note, just on the disconnect between what seems to be the current JS community trend and this.

1. The "cache" (haven't found any better wording so far) servs multiple purposes:
First is for aggreation purpose. Want to make it easy to differential or full-syncs, depending what you need. So on e.g. getPositions, the cache contains the your most up to date list positions. They aggrgate into the cache on position event until all positions collected, than position event will do incremental updates on that list. So we can have a PositionsUpdate.added, PositionsUpdate.changed, PositionsUpdate.removed and PositionsUpdate.all - we handle increment diffs already on the API.
Next reason is to be a ReplaySubject to the outside. It makes not much sense yet, but it will after next push / the introductoin of the subscription registry. This will make sure we never request same thing from TWS twice. So you can call getPositions() a 100x times, but instead of creating 100 subscriptions, you will create 100 observers on 1 subscription. Those new subscriber will never receive the "initial event" if we not rebuild a ReplaySubject, replaying currently cached value.

2. It's an ugly side-effect of behaving like a ReplaySubject, but otherwise new Observers won't get those ticks at all (e.g. sent after request and than never again - if you create a new Observer later on it will never see it until we replay it).
How about adding an ingressTimstamp to market data ticks?

3. I build an Angular web frontend, in parallel to the node REST backend. Angular is rxjs all the way, the controllers on serice are rxjs, ... all is rxjs... almost, the damn IBPlugin.ts is not. That's why I started IBApiNext, want to get rid of those ugly EventEmitter hacking accross the whole stack :D

Thanks for feedback! :)

**Comment by mfrener** [comment]
Pushed a new feature - the subscription registry.
What it does (from IBApiNext doc)
 * [[IBApiNext]] does return RxJS Observables on most of the functions.
 * The first subscriber will send the request to TWS, while the last un-subscriber will cancel it.
 * Any subscriber in between will get a replay of the latest received value(s).
 * This is also the case if you call same function with same arguments multiple times ([[IBApiNext]]
 * will make sure that a similar subscription is not requested multiple times from TWS, but it will
 * become a new observers to the existing subscription).
 * In case of an error, a re-subscribe will send the TWS request again (it is fully compatible to RxJS
 * operators, e.g. retry or retryWhen).

It also changes pattern of the get-function on IBApi, down to calling this.subscripton.register().
Callback implementations have been moved out of the function for code readability reason.

Nex stepst: bring consistency to APIs that provide updates. 
Example: PositionsUpdate has added/changed/removed/all while AccountSummariesUpdate only has changed/all and getContractDetails does not return updates at all, while internal  it gets result incrementally (e.g. you might want show first results already on UI while TWS is still delivering new ones).

**Comment by mfrener** [comment]
Pushed a major update. It includes a whole bunch of fixing optimization work.
Change and the interface is abou that Map is ReadyonlyMap.
There also UnitTests for all RxJS wrapper up to now https://github.com/stoqey/ib/tree/api-next/src/tests/unit/api-next
They will run also w/o a TWS connection, because it tests the Event -> RxJS code, generating the event my itself.
Run it with "yarn test-next". 
Next is to implement more functions.

**Comment by mfrener** [comment]
The current state is available for preview on master now.
IBApiNext tests on CI are enabled and README has been updated to cover IBApiNext as well.

**Pull request merged**
