### PR TITLE
Fix openOrder and completedOrder

### PR DESCRIPTION
**Pull request by mfrener**
Fix for https://github.com/stoqey/ib/issues/34
Not tested at my side, it was just a good guess as follow up on the decoder issue from yesterday. 
@Tsopic can't add you to reviewer list. I will wait with merge for your approval / confirmation that it works now.

### CODE REVIEW

**Comment by Tsopic** [comment]
I'm not sure how to consume this package outside npm/yarn. 

Any way I could use this branch as a package directly from package repo?

**Comment by mfrener** [comment]
> I'm not sure how to consume this package outside npm/yarn.
> 
> Any way I could use this branch as a package directly from package repo?
> 
> @mfrener

You can update it manually:
Do "npm run build" on root folder of this package. It will create /dist folder containing the transplanted .js files.
Than find the node_modules/@stoqey/ib folder on your App project and replace node_modules\@stoqey\ib\dist copy with the /dist from above.

**Review by ceddybi — APPROVED** [review]

**Comment by Tsopic** [comment]
Wasn't able to get it working just yet. Sent the errors in slack

**Comment by mfrener** [comment]
Closed this PR as it will be part of overhaul branch.
We will collect changes there first to avoid too much noise on the master.

**Pull request closed without merging**
